class AppConfig:

    PORT = 3978
    APP_ID = ""
    APP_PASSWORD = ""
    QNA_KNOWLEDGEBASE_ID = ""
    QNA_ENDPOINT_KEY = ""
    QNA_ENDPOINT_HOST = ""
    SUBSCRIPTION_KEY = ""
    SUBSCRIPTION_REGION = ""
